"""
UFC Sniper Dashboard - Streamlit Web Application
"""
import streamlit as st
from PIL import Image
from pathlib import Path
from ufc_predictor.inference.predict import predict_matchup, EXCLUDED_WEIGHT_CLASSES
from ufc_predictor.data.upcoming import get_upcoming_fight_data, get_recent_events, get_fight_card


# Page Configuration
st.set_page_config(
    page_title="UFC Sniper",
    page_icon="🎯",
    layout="wide"
)

# Weight Class Mapping (user-friendly names to internal format)
WEIGHT_CLASSES = {
    "Heavyweight (High Risk)": "Heavyweight Bout",
    "Light Heavyweight": "Light Heavyweight Bout",
    "Middleweight": "Middleweight Bout",
    "Welterweight": "Welterweight Bout",
    "Lightweight": "Lightweight Bout",
    "Featherweight": "Featherweight Bout",
    "Bantamweight": "Bantamweight Bout",
    "Flyweight (High Risk)": "Flyweight Bout",
    "Women's Bantamweight": "Women's Bantamweight Bout",
    "Women's Flyweight": "Women's Flyweight Bout",
    "Women's Strawweight (High Risk)": "Women's Strawweight Bout",
}


def generate_export_text(predictions, event):
    """
    Generate formatted markdown export of picks.

    Args:
        predictions: List of prediction dicts with fight and result info
        event: Event dict with event_name, date, location

    Returns:
        Formatted markdown string
    """
    lines = []

    # Header
    lines.append(f"# {event.get('event_name', 'UFC Event')}")
    lines.append(f"**Date:** {event.get('date', 'TBA')}")
    lines.append(f"**Location:** {event.get('location', 'TBA')}")
    lines.append("")

    # Separate sniper bets from passes
    sniper_bets = []
    passes = []
    no_odds = []

    for pred in predictions:
        if pred.get("has_odds"):
            if pred.get("is_sniper_bet"):
                sniper_bets.append(pred)
            else:
                passes.append(pred)
        else:
            no_odds.append(pred)

    # Sort by confidence (descending)
    sniper_bets.sort(key=lambda x: x['confidence'], reverse=True)
    passes.sort(key=lambda x: x['confidence'], reverse=True)
    no_odds.sort(key=lambda x: x['confidence'], reverse=True)

    # Sniper Bets Section
    if sniper_bets:
        lines.append("## 🎯 SNIPER BETS (Recommended)")
        lines.append("")
        for i, pred in enumerate(sniper_bets, 1):
            winner = pred['winner']
            loser = pred['loser']
            lines.append(f"{i}. **{winner}** vs {loser}")
            lines.append(f"   - Confidence: {pred['confidence']:.1f}%")
            lines.append(f"   - Odds: {pred['odds_f1']:+d} / {pred['odds_f2']:+d}")
            lines.append(f"   - Bet On: {winner} ({pred['winner_odds']:+d})")
            if 'ev' in pred:
                lines.append(f"   - Expected Value: {pred['ev']*100:+.1f}%")
            lines.append(f"   - Status: ✅ SNIPER BET")
            lines.append("")
        lines.append("")

    # Passes Section
    if passes:
        lines.append("## ⛔ PASS (Do Not Bet)")
        lines.append("")
        for i, pred in enumerate(passes, len(sniper_bets) + 1):
            winner = pred['winner']
            loser = pred['loser']
            lines.append(f"{i}. {pred['fighter1']} vs {pred['fighter2']}")
            lines.append(f"   - Prediction: **{winner}**")
            lines.append(f"   - Confidence: {pred['confidence']:.1f}%")
            lines.append(f"   - Odds: {pred['odds_f1']:+d} / {pred['odds_f2']:+d}")
            lines.append(f"   - Status: PASS")

            # Add reasons
            if pred.get('reasons'):
                reasons_text = ", ".join(pred['reasons'])
                lines.append(f"   - Reasons: {reasons_text}")
            lines.append("")
        lines.append("")

    # No Odds Section
    if no_odds:
        lines.append("## 📊 No Odds Available")
        lines.append("")
        for i, pred in enumerate(no_odds, len(sniper_bets) + len(passes) + 1):
            winner = pred['winner']
            lines.append(f"{i}. **{winner}** vs {pred['loser']}")
            lines.append(f"   - Confidence: {pred['confidence']:.1f}%")
            lines.append(f"   - Weight Class: {pred['weight_class'].replace(' Bout', '')}")

            # Determine if it would be a candidate
            is_high_conf = pred['confidence'] > 65
            is_safe_class = pred['weight_class'] not in EXCLUDED_WEIGHT_CLASSES
            if is_high_conf and is_safe_class:
                lines.append(f"   - Note: Would be Sniper candidate with odds")
            lines.append("")

    # Footer
    lines.append("---")
    lines.append("*Generated by UFC Sniper Dashboard*")

    return "\n".join(lines)


# Sidebar: Event Loader
with st.sidebar:
    st.header("📅 Event Selector")

    # Event source selection
    event_source = st.radio(
        "Select Event Source:",
        ["Next Upcoming Event", "Recent Completed Events"],
        label_visibility="collapsed"
    )

    if event_source == "Next Upcoming Event":
        if st.button("Load Next Event", type="primary", use_container_width=True):
            with st.spinner("Fetching fight card and odds..."):
                try:
                    card = get_upcoming_fight_data()
                    if card and card.get("fights"):
                        st.session_state["event"] = card
                        st.success("Event loaded!")
                    else:
                        st.error("Could not load fight card. Please try again.")
                except Exception as e:
                    st.error(f"Error loading event: {str(e)}")
    else:
        # Load recent events on first render or when button clicked
        if "recent_events" not in st.session_state:
            with st.spinner("Loading recent events..."):
                st.session_state["recent_events"] = get_recent_events(10)

        recent_events = st.session_state["recent_events"]

        if recent_events:
            event_names = [e["name"] for e in recent_events]
            selected_event = st.selectbox(
                "Select Event:",
                event_names,
                index=0 if "UFC 323" in event_names[0] else 0
            )

            if st.button("Load Selected Event", type="primary", use_container_width=True):
                with st.spinner(f"Fetching {selected_event}..."):
                    try:
                        # Find the URL for selected event
                        event_url = next(e["url"] for e in recent_events if e["name"] == selected_event)
                        card = get_fight_card(event_url)
                        if card and card.get("fights"):
                            st.session_state["event"] = card
                            st.success("Event loaded!")
                        else:
                            st.error("Could not load fight card. Please try again.")
                    except Exception as e:
                        st.error(f"Error loading event: {str(e)}")
        else:
            st.error("Could not fetch recent events")

    # Display loaded event info
    if "event" in st.session_state:
        event = st.session_state["event"]
        st.divider()
        st.caption("**Loaded Event:**")
        st.write(f"**{event.get('event_name', 'Unknown')}**")
        st.caption(f"{event.get('date', 'TBA')}")
        st.caption(f"{event.get('location', 'TBA')}")
        st.caption(f"{len(event.get('fights', []))} fights on card")

        # Export button (if predictions are available)
        if "predictions" in st.session_state and st.session_state["predictions"]:
            st.divider()
            export_text = generate_export_text(st.session_state["predictions"], event)
            event_name_clean = event.get('event_name', 'UFC_Event').replace(' ', '_').replace(':', '')
            st.download_button(
                label="📥 Export Picks",
                data=export_text,
                file_name=f"{event_name_clean}_picks.md",
                mime="text/markdown",
                use_container_width=True
            )


# Main Header
st.title("UFC Sniper 🎯")
st.subheader("AI-Powered Fight Prediction & Betting Engine")
st.divider()


# Main Area: Two-Tab Interface
tab1, tab2 = st.tabs(["🎯 Fight Card Analysis", "🔧 Manual Matchup"])


# Tab 1: Fight Card Analysis
with tab1:
    if "event" not in st.session_state:
        st.info("👈 Click 'Load Next Event' in the sidebar to analyze an upcoming fight card")
    else:
        event = st.session_state["event"]
        st.subheader(f"🏟️ {event['event_name']}")
        st.caption(f"{event['date']} • {event['location']}")
        st.divider()

        # Initialize predictions storage
        predictions = []

        # Loop through fights
        for fight in event["fights"]:
            try:
                # Get odds from scraped data
                odds_f1 = fight.get("odds_f1")
                odds_f2 = fight.get("odds_f2")

                # Run prediction with odds
                result = predict_matchup(
                    fight["fighter1"],
                    fight["fighter2"],
                    fight["weight_class"],
                    odds_f1=odds_f1,
                    odds_f2=odds_f2
                )

                # Determine display based on whether we have odds and Sniper verdict
                has_odds = odds_f1 is not None and odds_f2 is not None
                is_sniper_bet = has_odds and result.get("sniper", {}).get("is_sniper_bet", False)

                # Display as expander with visual indicator
                icon = "🎯" if is_sniper_bet else "⚪"
                label = f"{icon} {fight['fighter1']} vs {fight['fighter2']}"

                with st.expander(label, expanded=fight["is_main_event"]):
                    # Metrics row
                    col1, col2, col3, col4 = st.columns(4)
                    col1.metric("Prediction", result["winner"])
                    col2.metric("Confidence", f"{result['confidence']:.1f}%")
                    col3.metric(
                        "Weight Class",
                        fight["weight_class"].replace(" Bout", "")
                    )

                    # Show odds if available
                    if has_odds:
                        odds_display = f"{odds_f1:+d} / {odds_f2:+d}"
                        col4.metric("Odds", odds_display)
                    else:
                        col4.metric("Odds", "N/A")

                    # Status banner
                    if has_odds and "sniper" in result:
                        if result["sniper"]["is_sniper_bet"]:
                            st.success(f"🎯 SNIPER BET: {result['winner']} to win")
                        else:
                            reasons = ", ".join(result["sniper"]["reasons"])
                            st.warning(f"⛔ PASS: {reasons}")
                    else:
                        # No odds available - show candidate status
                        is_high_conf = result["confidence"] > 65
                        is_safe_class = fight["weight_class"] not in EXCLUDED_WEIGHT_CLASSES

                        if is_high_conf and is_safe_class:
                            st.info("📊 High confidence + Safe weight class (Odds needed for Sniper check)")
                        elif not is_high_conf:
                            st.warning(f"⚠️ Low confidence ({result['confidence']:.1f}% < 65%)")
                        elif not is_safe_class:
                            st.error("⛔ High-risk weight class")

                # Store prediction for export
                pred_data = {
                    "fighter1": fight["fighter1"],
                    "fighter2": fight["fighter2"],
                    "winner": result["winner"],
                    "loser": fight["fighter2"] if result["winner"] == fight["fighter1"] else fight["fighter1"],
                    "confidence": result["confidence"],
                    "weight_class": fight["weight_class"],
                    "has_odds": has_odds,
                }

                if has_odds:
                    pred_data["odds_f1"] = odds_f1
                    pred_data["odds_f2"] = odds_f2
                    pred_data["is_sniper_bet"] = is_sniper_bet

                    # Add winner's odds for export
                    if result["winner"] == fight["fighter1"]:
                        pred_data["winner_odds"] = odds_f1
                    else:
                        pred_data["winner_odds"] = odds_f2

                    # Add EV if available
                    if "ev_f1" in result and "ev_f2" in result:
                        if result["winner"] == fight["fighter1"]:
                            pred_data["ev"] = result["ev_f1"]
                        else:
                            pred_data["ev"] = result["ev_f2"]

                    # Add reasons if it's a pass
                    if not is_sniper_bet and "sniper" in result:
                        pred_data["reasons"] = result["sniper"].get("reasons", [])

                predictions.append(pred_data)

            except Exception as e:
                st.error(f"Error predicting {fight['fighter1']} vs {fight['fighter2']}: {str(e)}")

        # Store predictions in session state for export
        st.session_state["predictions"] = predictions


# Tab 2: Manual Matchup
with tab2:
    # Input Section
    col1, col2 = st.columns(2)

    with col1:
        fighter_a = st.text_input("Fighter A Name", placeholder="e.g., Islam Makhachev")

    with col2:
        fighter_b = st.text_input("Fighter B Name", placeholder="e.g., Dustin Poirier")

    # Weight class selection
    weight_class_display = st.selectbox(
        "Weight Class",
        options=list(WEIGHT_CLASSES.keys()),
        index=4  # Default to Lightweight
    )
    weight_class_internal = WEIGHT_CLASSES[weight_class_display]

    # Odds Section (collapsible)
    include_odds = st.checkbox("Include betting odds for EV calculation")

    odds_a = None
    odds_b = None

    if include_odds:
        col1, col2 = st.columns(2)
        with col1:
            odds_a = st.number_input(
                f"Odds for {fighter_a or 'Fighter A'} (American)",
                step=10,
                format="%d",
                value=-150
            )
        with col2:
            odds_b = st.number_input(
                f"Odds for {fighter_b or 'Fighter B'} (American)",
                step=10,
                format="%d",
                value=150
            )

    st.divider()

    # Action Button
    if st.button("Analyze Matchup", type="primary", use_container_width=True):
        # Validation
        if not fighter_a or not fighter_b:
            st.warning("⚠️ Please enter both fighter names")
        else:
            try:
                # Call prediction
                result = predict_matchup(
                    fighter_a,
                    fighter_b,
                    weight_class_internal,
                    odds_f1=odds_a if include_odds else None,
                    odds_f2=odds_b if include_odds else None
                )

                # Display Banner
                if include_odds and "sniper" in result:
                    if result["sniper"]["is_sniper_bet"]:
                        st.success(f"🎯 SNIPER BET FOUND: {result['winner']} to win")
                    else:
                        reasons = ", ".join(result["sniper"]["reasons"])
                        st.warning(f"⛔ PASS: {reasons}")
                else:
                    st.info(
                        f"📊 PREDICTION: {result['winner']} ({result['confidence']:.0f}%)"
                    )

                # Metrics Row
                col1, col2, col3 = st.columns(3)

                col1.metric("Confidence", f"{result['confidence']:.1f}%")
                col2.metric("Predicted Winner", result["winner"])

                # Expected Value
                if include_odds and "ev_f1" in result and "ev_f2" in result:
                    # Determine which fighter has the recommendation
                    if result["winner"] == fighter_a:
                        ev_display = f"{result['ev_f1'] * 100:+.1f}%"
                    else:
                        ev_display = f"{result['ev_f2'] * 100:+.1f}%"
                else:
                    ev_display = "—"

                col3.metric("Expected Value", ev_display)

            except Exception as e:
                st.error(f"Error making prediction: {str(e)}")
                st.caption(
                    "This might occur if fighters are not in the database. "
                    "Try checking spelling or using full names."
                )


# Strategy Context Section
st.divider()
st.subheader("📈 Sniper Strategy Heatmap")

heatmap_path = Path("output/plots/sniper_heatmap.png")
if heatmap_path.exists():
    try:
        img = Image.open(heatmap_path)
        st.image(img, caption="Green Zones = Profitable Betting Areas", use_container_width=True)
    except Exception as e:
        st.caption(f"Could not load heatmap: {str(e)}")
else:
    st.caption("Heatmap not found. Generate it by running: `python scripts/plot_sniper_heatmap.py`")
